
export const CHANGE_NAME = 'CHANGE_NAME';

// Auth Action types
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const AUTH_LOADING = 'AUTH_LOADING';

// Profile action types
export const PROFILE_USER_DETAILS_FETCHED = 'PROFILE_USER_DETAILS_FETCHED';
export const PROFILE_USER_DETAILS_FETCH_ERROR = 'PROFILE_USER_DETAILS_FETCH_ERROR';

export const PROFILE_ARTICLES_FETCHING = 'PROFILE_ARTICLES_FETCHING';
export const PROFILE_ARTICLES_FETCHED = 'PROFILE_ARTICLES_FETCHED';
export const PROFILE_ARTICLES_FETCH_ERROR = 'PROFILE_ARTICLES_FETCH_ERROR';

export const PROFILE_FOLLOWERS_FETCHING = 'PROFILE_FOLLOWERS_FETCHING';
export const PROFILE_FOLLOWERS_FETCHED = 'PROFILE_FOLLOWERS_FETCHED';
export const PROFILE_FOLLOWERS_FETCH_ERROR = 'PROFILE_FOLLOWERS_FETCH_ERROR';

export const PROFILE_FOLLOWING_FETCHING = 'PROFILE_FOLLOWING_FETCHING';
export const PROFILE_FOLLOWING_FETCHED = 'PROFILE_FOLLOWING_FETCHED';
export const PROFILE_FOLLOWING_FETCH_ERROR = 'PROFILE_FOLLOWING_FETCH_ERROR';

export const PROFILE_DETAILS_UPDATING = 'PROFILE_DETAILS_UPDATING';
export const PROFILE_DETAILS_UPDATED = 'PROFILE_DETAILS_UPDATED';
export const PROFILE_DETAILS_UPDATE_ERROR = 'PROFILE_DETAILS_UPDATE_ERROR';

export const PROFILE_RESET_EDIT_STATE = 'PROFILE_RESET_EDIT_STATE';
